#!/usr/bin/env bash
# Prints the Homebrew formula for an `x8ai` release, for the tap
# (github.com/<owner>/homebrew-tap, Formula/x8ai.rb), so that
# `brew install <owner>/tap/x8ai` installs it.
set -euo pipefail

version="${1:?usage: homebrew-formula.sh <version> <sha256> [owner]}"
sha256="${2:?usage: homebrew-formula.sh <version> <sha256> [owner]}"
owner="${3:-aashirvad08}"

cat <<FORMULA
# Generated by scripts/release/homebrew-formula.sh in $owner/x8ai-workspace.
class X8ai < Formula
  desc "Terminal-first workspace for coding with AI agents"
  homepage "https://github.com/$owner/x8ai-workspace"
  url "https://github.com/$owner/x8ai-workspace/releases/download/v$version/x8ai-$version-macos.tar.gz"
  version "$version"
  sha256 "$sha256"

  depends_on :macos

  def install
    bin.install "x8ai"
  end

  def caveats
    <<~EOS
      Run \`x8ai\` to open x8ai Workspace in this terminal.
    EOS
  end

  test do
    assert_equal "x8ai #{version}", shell_output("#{bin}/x8ai --version").strip
  end
end
FORMULA
